#ifndef __LIB_LOG__
#define __LIB_LOG__

#define BAD_ALLOC_LOG "BAD_ALLOC"
#define SNMP_LOG "SNMP LOG" 
#define SNMP_ASK_LOG "ASK SNMP"
#define SELECT_LOG "SELECT"
#define SNMP_INIT_SESSION "SNMP INIT SESSION"
#define SNMP_MANAGER_STOP "MANAGER STOP"
#define SNMP_MANAGER_RESTART "MANAGER RESTART"

#endif